DLP = record_data["DLP"]
        Date = record_data["record_date"]
        Facility = record_data["facility"]
        Doctors = record_data["co_reporting_doctor"]
        UID = record_data["patient-details"]

        current_correlated = record_data['correlated_case_count']
        #current_live = record_data['live_case_count']
        #current_library = record_data['library_case_count']
        #current_course = record_data['live_case_course_count']
        current_native_coronary= record_data['is_native_coronary']
        current_non_cardiac = record_data['non_cardiac_count']
        current_non_coronary= record_data['non_coronary_count']
        current_cardiac = record_data['cardiac_count']
        current_gta = record_data['gta_count']
